//
//  NFNReceiptRecognitionViewController.m
//  ios-receipt-scan-example
//
//  Version 0.0.1
//
//  The MIT License (MIT)
//
//  Copyright (c) 2015 Paulo Miguel Almeida Rodenas <paulo.ubuntu@gmail.com>
//
//  Get the latest version from here:
//
//  https://github.com/nfscan/ios-receipt-scan-example
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//

#import "NFNReceiptRecognitionViewController.h"

@interface NFNReceiptRecognitionViewController()

// Components
/**
 *  data view container reference
 */
@property (weak, nonatomic) IBOutlet UIView *dataView;
/**
 *  thankyou container reference
 */
@property (weak, nonatomic) IBOutlet UIView *thankYouView;

/**
 *  cnpj text field reference
 */
@property (weak, nonatomic) IBOutlet UITextField *cnpjTextField;
/**
 *  coo text field reference
 */
@property (weak, nonatomic) IBOutlet UITextField *cooTextField;
/**
 *  date text field reference
 */
@property (weak, nonatomic) IBOutlet UITextField *dataTextField;
/**
 *  total text field reference
 */
@property (weak, nonatomic) IBOutlet UITextField *totalTextField;
/**
 *  donate button reference
 */
@property (weak, nonatomic) IBOutlet UIButton *donateButton;

// Delegates
/**
 *  cnpj formatter delegate reference
 */
@property (strong, nonatomic) CNPJFormatterTextFieldDelegate* cnpjFormatterDelegate;
/**
 *  date formatter delegate reference
 */
@property (strong, nonatomic) DateFormatterTextFieldDelegate* dateFormatterDelegate;
/**
 *  currency formatter delegate reference
 */
@property (strong, nonatomic) CurrencyFormatterTextFieldDelegate* currencyFormatterTextFieldDelegate;
/**
 *  coo formatter delegate reference
 */
@property (strong, nonatomic) COOFormatterTextFieldDelegate* cooFormatterTextFieldDelegate;

// Http
/**
 *  OCR service reference
 */
@property (strong, nonatomic) NFNOCRService* ocrService;

// Security
/**
 *  transaction id got from OCR service
 */
@property (strong, nonatomic) NSString* transactionId;
/**
 *  counter signature generated by this app
 */
@property (strong, nonatomic) NSString* counterSignature;

// Flow
/**
 *  Receipt got from OCR service reference
 */
@property (strong, nonatomic) TaxReceipt* receipt;
/**
 *  NSTimer for waiting until finish processing
 */
@property (strong, nonatomic) NSTimer *timer;
/**
 *  amount of times we hit the process check endpoint
 */
@property (nonatomic) int numberOfProcessCheckDone;

@end

@implementation NFNReceiptRecognitionViewController

#pragma mark - UIViewController lifecycle

/**
 *  Called after the controller's view is loaded into memory.
 *  This method is called after the view controller has loaded its view hierarchy into memory. This method is called regardless of whether the view hierarchy was loaded from a nib file or created programmatically in the loadView method. You usually override this method to perform additional initialization on views that were loaded from nib files.
 */
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    // Init OCR service instance
    self.ocrService = [[NFNOCRService alloc] init];
    self.ocrService.delegate = self;
    
    [self setupUI];
}

/**
 *  Method the prepares the custom compoenents when viewDidLoad event happens
 */
-(void) setupUI{
    
    MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
    hud.mode = MBProgressHUDModeIndeterminate;
    hud.labelText = @"Processando";
    
    // Setting delegates to each UITextField
    self.cnpjFormatterDelegate = [[CNPJFormatterTextFieldDelegate alloc] init];
    self.dateFormatterDelegate = [[DateFormatterTextFieldDelegate alloc] init];
    self.currencyFormatterTextFieldDelegate = [[CurrencyFormatterTextFieldDelegate alloc] init];
    self.cooFormatterTextFieldDelegate = [[COOFormatterTextFieldDelegate alloc] init];
    self.cnpjTextField.delegate = self.cnpjFormatterDelegate;
    self.dataTextField.delegate = self.dateFormatterDelegate;
    self.totalTextField.delegate = self.currencyFormatterTextFieldDelegate;
    self.cooTextField.delegate = self.cooFormatterTextFieldDelegate;
    
    // Add Targets for Form validation
    [self.cnpjTextField  addTarget:self action:@selector(validateFormField:) forControlEvents:UIControlEventEditingChanged];
    [self.dataTextField  addTarget:self action:@selector(validateFormField:) forControlEvents:UIControlEventEditingChanged];
    [self.cooTextField   addTarget:self action:@selector(validateFormField:) forControlEvents:UIControlEventEditingChanged];
    [self.totalTextField addTarget:self action:@selector(validateFormField:) forControlEvents:UIControlEventEditingChanged];

    
    [self.ocrService requestProcessAuth];
}


#pragma mark - Action methods

/**
 *  Called when touch up event is fired for dataView
 *
 *  @param sender instance to the component that fired this event
 */
- (IBAction)touchUpDataView:(id)sender {
    [self.view endEditing:YES];
}

/**
 *  Called when touch up event is fired for camera button
 *
 *  @param sender instance to the component that fired this event
 */
- (IBAction)cameraButtonHandler:(id)sender {
    [self dismissViewControllerAnimated:YES completion:nil];
}

/**
 *  Called when touch up event is fired for donate button
 *
 *  @param sender instance to the component that fired this event
 */
- (IBAction)donateButtonHandler:(id)sender {
    self.dataView.hidden = YES;
    
    NSDateFormatter * dateFormatter = [[NSDateFormatter alloc] init];
    dateFormatter.dateFormat = [Constants DATE_FORMAT];
    
    self.receipt.cnpj = [self.cnpjTextField.text removeNonNumeric];
    self.receipt.date = [dateFormatter dateFromString:self.dataTextField.text];
    self.receipt.coo = self.cooTextField.text;
    self.receipt.total = [self.totalTextField.text doubleValue];
    
    MBProgressHUD *hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
    hud.mode = MBProgressHUDModeIndeterminate;
    
    __weak typeof(self) weakSelf = self;
    
    dispatch_queue_t serverDelaySimulationThread = dispatch_queue_create("com.github.nfscan.ios-receipt-scan-example.serverUpload", nil);
    dispatch_async(serverDelaySimulationThread, ^{
        dispatch_async(dispatch_get_main_queue(), ^{
            [weakSelf.ocrService requestDonate:weakSelf.transactionId receipt:weakSelf.receipt];
        });
    });
    
}

#pragma mark - Network methods

/**
 *  Method called when the response is successfully received (HTTP Code 200) and parsed into a JSON array
 *
 *  @param identifier identifies which request this response if from
 *  @param jsonArray  a JSON array containing the response got from server
 */
-(void) sucessOnRequest:(RequestIdentifier)identifier jsonResponse:(NSDictionary *)jsonArray
{
#ifdef DEBUG
    NSLog(@"%s",__PRETTY_FUNCTION__);
#endif
    
    if(identifier == PROCESS_AUTH_REQUEST)
    {

        self.transactionId = [jsonArray valueForKey:@"transactionId"];
        NSString* signature = [jsonArray valueForKey:@"signature"];
        
        PassCode *passCode = [[PassCode alloc] init];
        if([passCode validatePass:signature])
        {
            CounterSignCode* counterSign = [[CounterSignCode alloc] init];
            self.counterSignature = [counterSign generate:signature];
            
            [self.ocrService requestProcessStart:self.transactionId counterSignature:self.counterSignature receipt:self.image];
        }
        else
        {
            [self errorOnRequest:PROCESS_AUTH_REQUEST jsonResponse:jsonArray];
        }
        
    }else if(identifier == PROCESS_START_REQUEST)
    {
        self.timer = [NSTimer scheduledTimerWithTimeInterval: 3.0 target: self selector: @selector(checkProcessingStatus) userInfo: nil repeats: YES];
    }
    else if(identifier == PROCESS_CHECK_REQUEST)
    {
        NSDictionary* ocrTransactionJSON = [jsonArray valueForKey:@"ocrTransaction"];
        if([[ocrTransactionJSON valueForKey:@"processed"]boolValue])
        {
            [self.timer invalidate];
            [MBProgressHUD hideHUDForView:self.view animated:YES];
            
            self.dataView.hidden = NO;
            self.thankYouView.hidden = YES;
            
            NSDateFormatter * dateFormatter = [[NSDateFormatter alloc] init];
            dateFormatter.dateFormat = [Constants DATE_FORMAT];
            
            TaxReceipt *receipt = [[TaxReceipt alloc] init];
            receipt.cnpj = [ocrTransactionJSON valueForKey:@"cnpj"];
            receipt.coo = [ocrTransactionJSON valueForKey:@"coo"];
            receipt.date = [dateFormatter dateFromString:[ocrTransactionJSON valueForKey:@"date"]] ;
            receipt.total = [[ocrTransactionJSON valueForKey:@"total"] doubleValue];
            
            self.cnpjTextField.text = receipt.cnpj;
            self.cooTextField.text = receipt.coo;
            self.dataTextField.text = [dateFormatter stringFromDate:receipt.date];
            self.totalTextField.text = [NSString stringWithFormat:@"%.2f", receipt.total];
            
            // Formatting data for the first time since it doesn't fire a UIControlEventEditingChanged event
            [self.cnpjFormatterDelegate reformat:self.cnpjTextField];
            [self.dateFormatterDelegate reformat:self.dataTextField];
            [self.cooFormatterTextFieldDelegate reformat:self.cooTextField];
            [self.currencyFormatterTextFieldDelegate reformat:self.totalTextField];
            
            // Validate whether or not we enable the doneButton. It's useful for when all field are being recognized somehow.
            [self validateInputTextFieldContents];

            
            self.receipt = receipt;
        }
    }
    else if(identifier == DONATE_REQUEST)
    {
        [MBProgressHUD hideHUDForView:self.view animated:YES];
        self.dataView.hidden = YES;
        self.thankYouView.hidden = NO;
    }
}

/**
 *  Method called when the response isn't received (HTTP Code != 200) correctly
 *
 *  @param identifier identifies which request this response if from
 *  @param jsonArray  a JSON array containing the response got from server if any
 */
-(void) errorOnRequest:(RequestIdentifier)identifier jsonResponse:(NSDictionary *)jsonArray
{
#ifdef DEBUG
    NSLog(@"%s",__PRETTY_FUNCTION__);
#endif
    
    [MBProgressHUD hideHUDForView:self.view animated:YES];
    
    NSString* alertMessage;
    
    if([NetworkAvailabilityUtils isConnected])
    {
        alertMessage = @"Something went wrong";
    }
    else
    {
        alertMessage = @"No connection to internet";
    }
    
    
    UIAlertController *alertController = [UIAlertController
                                          alertControllerWithTitle:@"Error"
                                          message:alertMessage
                                          preferredStyle:UIAlertControllerStyleAlert];
    UIAlertAction *okAction = [UIAlertAction
                               actionWithTitle:NSLocalizedString(@"OK", @"OK action")
                               style:UIAlertActionStyleDefault
                               handler:^(UIAlertAction *action)
                               {
                                   [self.navigationController popViewControllerAnimated:YES];
                               }];
    
    [alertController addAction:okAction];
    [self presentViewController:alertController animated:YES completion:nil];
}

#pragma mark - Utility methods

/**
 *  Method called to request the process check endpoint and check whether or not the nfscan-server process has finished or not
 */
-(void) checkProcessingStatus
{
#ifdef DEBUG
    NSLog(@"%s",__PRETTY_FUNCTION__);
#endif
    self.numberOfProcessCheckDone += 1;
    if (self.numberOfProcessCheckDone < 30) // 90 seconds
    {
        [self.ocrService requestProcessCheck:self.transactionId counterSignature:self.counterSignature];
    }
    else
    {
        [self.timer invalidate];
        
        [MBProgressHUD hideHUDForView:self.view animated:YES];

        UIAlertController *alertController = [UIAlertController
                                              alertControllerWithTitle:@"Error"
                                              message:@"An OCR process timeout has occurred. Are absolutely sure you're running the OCR service ?"
                                              preferredStyle:UIAlertControllerStyleAlert];
        UIAlertAction *okAction = [UIAlertAction
                                   actionWithTitle:NSLocalizedString(@"OK", @"OK action")
                                   style:UIAlertActionStyleDefault
                                   handler:^(UIAlertAction *action)
                                   {
                                       [self.navigationController popViewControllerAnimated:YES];
                                   }];
        
        [alertController addAction:okAction];
        [self presentViewController:alertController animated:YES completion:nil];
        
    }
}

/**
 *  Validate whether or not the input text for a specific text field
 *
 *  @param textField text field we want to validate
 */
-(void) validateFormField:(UITextField *)textField
{
    if(textField == self.cnpjTextField )
    {
        [self.cnpjFormatterDelegate reformat:self.cnpjTextField];
    }
    else if(textField == self.dataTextField )
    {
        [self.dateFormatterDelegate reformat:self.dataTextField];
    }
    else if(textField == self.cooTextField )
    {
        [self.cooFormatterTextFieldDelegate reformat:self.cooTextField];
    }
    else if(textField == self.totalTextField )
    {
        [self.currencyFormatterTextFieldDelegate reformat:self.totalTextField];
    }
    
    // Validate whether or not we enable the doneButton
    [self validateInputTextFieldContents];
    
}

/**
 *  Method that validates whether or not we can enable the donate button
 */
-(void) validateInputTextFieldContents
{
#ifdef DEBUG
    NSLog(@"%s self.cnpjFormatterDelegate: %d",__PRETTY_FUNCTION__, [self.cnpjFormatterDelegate validarCNPJ:[self.cnpjTextField.text removeNonNumeric]]);
    NSLog(@"%s self.dateFormatterDelegate: %d",__PRETTY_FUNCTION__, [self.dateFormatterDelegate validateDate:[self.dataTextField.text removeNonNumeric]]);
    NSLog(@"%s self.cooTextField.text.length == 6: %d",__PRETTY_FUNCTION__, self.cooTextField.text.length == 6);
    NSLog(@"%s [self.totalTextField.text doubleValue] > 0.f: %d",__PRETTY_FUNCTION__, [self.totalTextField.text doubleValue] > 0.f);
#endif
    
    [self.donateButton setEnabled:(
                                 [self.cnpjFormatterDelegate validarCNPJ:[self.cnpjTextField.text removeNonNumeric]] &&
                                 [self.dateFormatterDelegate validateDate:[self.dataTextField.text removeNonNumeric]] &&
                                 self.cooTextField.text.length == 6 &&
                                 [self.totalTextField.text doubleValue] > 0.f
                                 )];
}



@end
